---
# make it mine

- name: copy.bashrc
  copy: 
    src: "files/hidden/.bashrc"
    dest: "{{ my_home_dir }}/"
    owner:  "{{ my_username }}"
    group:  "{{ my_username }}"
    mode:  0644
    backup: yes

- name: copy.exrc
  copy:
    src: "files/hidden/.exrc"
    dest: "{{ my_home_dir }}/"
    owner: "{{ my_username }}"
    group: "{{ my_username }}"
    mode:  0644
    backup: yes

- name: copy.vimrc become become
  become: yes
  copy:
    src: "files/hidden/.vimrc"
    dest: "/root/"
    owner: root
    group: root
    mode:  0644
    backup: yes

- name: copy.vimrc
  copy:
    src: "files/hidden/.vimrc"
    dest: "{{ my_home_dir }}/"
    owner: "{{ my_username }}"
    group: "{{ my_username }}"
    mode:  0644
    backup: yes

- name: copy.etc/motd
  become: yes
  template:
    src: "motd.j2"
    dest: "/etc/motd"
    owner: root
    mode: 0755


- name: copy.set permissions
  file:
    path: "/usr/local/bin"
    mode: 0777
  become: yes
    
- name: copy.usr/local/bin/motd 
  copy: 
    src: "files/motd"
    dest: "/usr/local/bin"
    owner: root
    mode: 0755
    force: no
  become: yes


 
    
       
