---
# make it mine

- name: copy.bashrc
  copy: 
    src: "files/hidden/.bashrc"
    dest: "{{ my_home_dir }}/"
    owner:  "{{ my_username }}"
    group:  "{{ my_username }}"
    mode:  0644
    backup: yes

- name: copy.exrc
  copy:
    src: "files/hidden/.exrc"
    dest: "{{ my_home_dir }}/"
    owner: "{{ my_username }}"
    group: "{{ my_username }}"
    mode:  0644
    backup: yes

- name: copy.etc/motd
  copy:
    dest: "/etc/motd"
    owner: root
    mode: 0755
    content: |
       echo "*********************************"
       echo " "
       echo " " 
       echo "{{ server_motd }}"
       echo " "
       echo " "
       echo "*********************************"
    force: no   


- name: copy.set permissions
  file:
    path: "/usr/local/bin"
    mode: 0777
  become: yes
    
- name: copy.usr/local/bin/motd 
  copy: 
    src: "files/motd"
    dest: "/usr/local/bin"
    owner: root
    mode: 0755
    force: no
  become: yes


 
    
       
