---
# vim

- name: vim.assert directories | debug
  debug: var=ansible_env.HOME

- name: vim.apt
  apt:
    name: 
      - vim
    state: latest
  become: yes
  when: ansible_facts['pkg_mgr'] == 'apt'

- name: vim.yum
  yum:
    name: 
      - vim
    state: latest
  become: yes
  when: ansible_facts['pkg_mgr'] == 'yum'

- name: vim.assert directories
  file:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: directory
  with_items:
    - ".vim"
    - ".vim/bundle"

- name: vim.git clone vim
  git: 
    repo:  "https://github.com/VundleVim/Vundle.vim.git"
    dest:  "{{ ansible_env.HOME }}/.vim/bundle/Vundle.vim"
    update: yes

- name: vim.install plugins
  command: vim +PluginInstall +qall
  register: plugins

